---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp-deployment
  name: webapp-service
  namespace: library-api
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp-deployment
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp-deployment
  name: webapp-deployment
  namespace: library-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-deployment
  template:
    metadata:
      labels:
        app: webapp-deployment
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: webapp-app-conf
        image: rafahcsilva/k8s_libraryapi-app:1.4.2
        name: webapp-php-container
        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: 0.2
            memory: 256Mi
          requests:
            cpu: 0.1
            memory: 200Mi
      - command:
        - nginx
        - -g
        - daemon off;
        image: nginx:1.14.2
        name: webapp-nginx-container
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 0.1
            memory: 128Mi
          requests:
            cpu: 0.05
            memory: 100Mi
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: webapp-configmap-volume
        - mountPath: /var/www/html/public
          name: webapp-indexmap-volume
      volumes:
      - configMap:
          items:
          - key: nginx.conf
            path: nginx.conf
          name: webapp-nginxconf-map
        name: webapp-configmap-volume
      - configMap:
          items:
          - key: index.php
            path: index.php
          name: webapp-nginxindex-map
        name: webapp-indexmap-volume
---
apiVersion: v1
data:
  APP_DEBUG: "true"
  APP_ENV: local
  APP_KEY: base64:vw6G2uP8LV22haEERtzr5yDCBraLrMwbxlbSJDA97uk=
  APP_NAME: appLibrary
  APP_URL: libraryapi.test
  AWS_ACCESS_KEY_ID: ""
  AWS_BUCKET: ""
  AWS_DEFAULT_REGION: us-east-1
  AWS_SECRET_ACCESS_KEY: ""
  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  DB_CONNECTION: mysql
  DB_DATABASE: library_admin
  DB_HOST: mysql-service
  DB_PASSWORD: testes
  DB_PORT: "3306"
  DB_USERNAME: root
  LOG_CHANNEL: stderr
  LOG_STDERR_FORMATTER: Monolog\Formatter\JsonFormatter
  MAIL_DRIVER: smtp
  MAIL_ENCRYPTION: "null"
  MAIL_HOST: smtp.mailtrap.io
  MAIL_PASSWORD: "null"
  MAIL_PORT: "2525"
  MAIL_USERNAME: "null"
  PUSHER_APP_CLUSTER: mt1
  PUSHER_APP_ID: ""
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""
  QUEUE_CONNECTION: database
  REDIS_HOST: redis-service
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"
  SESSION_DRIVER: redis
  SESSION_LIFETIME: "120"
kind: ConfigMap
metadata:
  labels:
    name: webapp-app-conf
  name: webapp-app-conf
  namespace: library-api
---
apiVersion: v1
data:
  index.php: <?php echo "sou fake";
kind: ConfigMap
metadata:
  name: webapp-nginxindex-map
  namespace: library-api
---
apiVersion: v1
data:
  nginx.conf: |-
    server {
        listen 80;
        index index.php index.html;
        root /var/www/html/public;
        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass localhost:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
        location / {
            try_files $uri $uri/ /index.php?$query_string;
            gzip_static on;
        }
    }
kind: ConfigMap
metadata:
  name: webapp-nginxconf-map
  namespace: library-api

