version: '3'

services:
  web:
    container_name: l6fs_web
    image: nginx:1.19-alpine
    depends_on:
      - app
    volumes:
      - ./default.nginx:/etc/nginx/conf.d/default.conf
      - ../src/:/var/www/html:rw
    ports:
      - 80:80
    networks:
      - backend
      - frontend


  app:
    container_name: l6fs_app
    build:
      context: ../
      dockerfile: ./Docker/app.Dockerfile
    image: rafahcsilva/k8s_laravel6fs-app:1.0.0
    command: [ "php-fpm" ]
    networks:
      - backend
    #    depends_on:
    #      - redis
    #      - mysql
    #    links:
    #      - mysql
    #      - redis
    # volumes:
    #   - ./src/:/app:rw
    environment:
      APP_NAME: "Laravel v6.x FullStack"
      APP_ENV: local
      APP_KEY: base64:T6RjNP9tM3O12uuieaRZCQgWYRnLwqfv/RelaiT4r7k=
      APP_DEBUG: (true)
      APP_URL: http://laravel6fs.test

      LOG_CHANNEL: stderr
      LOG_STDERR_FORMATTER: Monolog\Formatter\JsonFormatter

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: l6fs
      DB_USERNAME: teste
      DB_PASSWORD: secret

      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379

      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      BROADCAST_DRIVER: redis
      QUEUE_CONNECTION: sync
      SESSION_LIFETIME: 120


  mysql:
    container_name: l6fs_db
    image: mysql:latest
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: l6fs
      MYSQL_USER: teste
      MYSQL_PASSWORD: secret


  redis:
    container_name: l6fs_redis
    image: redis:alpine
    networks:
      - backend
    volumes:
      - redis-data:/data


volumes:
  redis-data:
    driver: "local"


networks:
  frontend:
  backend:
