# App

apiVersion: v1
kind: Service
metadata:
  namespace: library-api
  name: app-service
  labels:
    app: app-deployment
spec:
  type: NodePort
  ports:
    - port: 9000
      protocol: TCP
      nodePort: 30080
  selector:
    app: app-deployment

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: library-api
  name: app-deployment
  labels:
    app: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-deployment
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
        - name: app-deployment
          image: rafahcsilva/k8s_libraryapi-app:1.3.0
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-conf

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: library-api
  name: app-conf
  labels:
    name: app-conf
data:
  APP_NAME: appLibrary
  APP_ENV: local
  APP_KEY: "base64:vw6G2uP8LV22haEERtzr5yDCBraLrMwbxlbSJDA97uk="
  APP_DEBUG: "true"
  APP_URL: http://localhost
  LOG_CHANNEL: stderr
  DB_CONNECTION: mysql
  DB_HOST: mysql-service
  DB_PORT: "3306"
  DB_DATABASE: library_admin
  DB_USERNAME: root
  DB_PASSWORD: testes
  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: redis
  SESSION_LIFETIME: "120"
  REDIS_HOST: redis-service
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"
  MAIL_DRIVER: smtp
  MAIL_HOST: smtp.mailtrap.io
  MAIL_PORT: "2525"
  MAIL_USERNAME: "null"
  MAIL_PASSWORD: "null"
  MAIL_ENCRYPTION: "null"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION: us-east-1
  AWS_BUCKET: ""
  PUSHER_APP_ID: ""
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""
  PUSHER_APP_CLUSTER: mt1
