version: '2'

services:
  app:
    build:
      context: ../
      dockerfile: ./Docker/app.Dockerfile
    image: rafahcsilva/k8s_libraryapi-app:1.3.0
    # commands testes
    #command: [ "php", "artisan", "schedulerInutil:run" ]
    #command: [ "php", "artisan", "cuspirlog:run", "--parametrozao=valorAqui" ]
    environment:
      APP_KEY: base64:a89Bj62VIrzfDCsb3m8BNU+JedVKtEZEmqif25fR2g0=
      APP_ENV: local
      DB_PORT: 3306
      DB_USERNAME: sandbox
      DB_DATABASE: library_admin
      DB_PASSWORD: sandbox
      DB_HOST: mysql
      MYSQL_HOST: mysql
      REDIS_HOST: redis
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      DEBUG: 1
      LOG_CHANNEL: stderr
      LOG_STDERR_FORMATTER: Monolog\Formatter\JsonFormatter
